import { http } from './http';

export const api = {
  auth: {
    login: (payload) => http.post('/auth/login', payload),
    register: (payload) => http.post('/auth/register', payload),
    forgotPassword: (payload) => http.post('/auth/forgot-password', payload),
    logout: () => http.post('/auth/logout'),
    me: () => http.get('/auth/me'),
  },
  dashboard: {
    overview: () => http.get('/dashboard/overview'),
  },
  analytics: {
    metrics: (params) => http.get('/analytics/metrics', { params }),
  },
  leads: {
    list: (params) => http.get('/leads', { params }),
    recent: () => http.get('/leads?limit=10&sort=-createdAt'),
    create: (payload) => http.post('/leads', payload),
    update: (id, payload) => http.put(`/leads/${id}`, payload),
    remove: (id) => http.delete(`/leads/${id}`),
    note: (id, payload) => http.post(`/leads/${id}/notes`, payload),
    assign: (id, payload) => http.patch(`/leads/${id}/assign`, payload),
    status: (id, payload) => http.patch(`/leads/${id}/status`, payload),
    score: (id, payload) => http.patch(`/leads/${id}/score`, payload),
    convert: (id, payload) => http.post(`/leads/${id}/convert`, payload),
  },
  contacts: {
    list: (params) => http.get('/contacts', { params }),
    create: (payload) => http.post('/contacts', payload),
    update: (id, payload) => http.put(`/contacts/${id}`, payload),
    remove: (id) => http.delete(`/contacts/${id}`),
    note: (id, payload) => http.post(`/contacts/${id}/notes`, payload),
    assign: (id, payload) => http.patch(`/contacts/${id}/assign`, payload),
    setCompany: (id, payload) => http.patch(`/contacts/${id}/company`, payload),
    deals: (id) => http.get(`/contacts/${id}/deals`),
  },
  companies: {
    list: (params) => http.get('/companies', { params }),
    create: (payload) => http.post('/companies', payload),
    update: (id, payload) => http.put(`/companies/${id}`, payload),
    remove: (id) => http.delete(`/companies/${id}`),
    get: (id) => http.get(`/companies/${id}`),
    note: (id, payload) => http.post(`/companies/${id}/notes`, payload),
    assign: (id, payload) => http.patch(`/companies/${id}/assign`, payload),
    contacts: (id) => http.get(`/companies/${id}/contacts`),
    deals: (id) => http.get(`/companies/${id}/deals`),
  },
  deals: {
    list: (params) => http.get('/deals', { params }),
    create: (payload) => http.post('/deals', payload),
    update: (id, payload) => http.put(`/deals/${id}`, payload),
    remove: (id) => http.delete(`/deals/${id}`),
    stage: (id, payload) => http.patch(`/deals/${id}/stage`, payload),
    reorder: (id, payload) => http.patch(`/deals/${id}/reorder`, payload),
    assign: (id, payload) => http.patch(`/deals/${id}/assign`, payload),
    addProducts: (id, payload) => http.post(`/deals/${id}/products`, payload),
    won: (id) => http.post(`/deals/${id}/won`),
    lost: (id, payload) => http.post(`/deals/${id}/lost`, payload),
    recordPayment: (id, payload) => http.post(`/deals/${id}/payment`, payload),
  },
  tasks: {
    list: (params) => http.get('/tasks', { params }),
    create: (payload) => http.post('/tasks', payload),
    update: (id, payload) => http.put(`/tasks/${id}`, payload),
    remove: (id) => http.delete(`/tasks/${id}`),
    status: (id, payload) => http.patch(`/tasks/${id}/status`, payload),
    assign: (id, payload) => http.patch(`/tasks/${id}/assign`, payload),
    overdue: () => http.get('/tasks/overdue/list'),
    upcoming: (params) => http.get('/tasks/upcoming/list', { params }),
  },
  products: {
    list: (params) => http.get('/products', { params }),
    create: (payload) => http.post('/products', payload),
    update: (id, payload) => http.put(`/products/${id}`, payload),
    remove: (id) => http.delete(`/products/${id}`),
    toggle: (id) => http.patch(`/products/${id}/toggle`),
    stats: () => http.get('/products/stats/sales'),
  },
  payments: {
    list: (params) => http.get('/payments', { params }),
    create: (payload) => http.post('/payments', payload),
    update: (id, payload) => http.put(`/payments/${id}`, payload),
    remove: (id) => http.delete(`/payments/${id}`),
    record: (payload) => http.post('/payments/record', payload),
    status: (id, payload) => http.patch(`/payments/${id}/status`, payload),
  },
  activities: {
    list: (params) => http.get('/activities', { params }),
    create: (payload) => http.post('/activities', payload),
    remove: (id) => http.delete(`/activities/${id}`),
    timeline: (entityType, entityId) => http.get(`/activities/timeline/${entityType}/${entityId}`),
  },
  notifications: {
    list: () => http.get('/notifications'),
    markRead: (id) => http.patch(`/notifications/${id}/read`),
  },
  profile: {
    update: (payload) => http.put('/profile', payload),
  },
  users: {
    list: (params) => http.get('/users', { params }),
    create: (payload) => http.post('/users', payload),
    update: (id, payload) => http.put(`/users/${id}`, payload),
    remove: (id) => http.delete(`/users/${id}`),
  },
  search: {
    query: (q) => http.get('/search', { params: { q } }),
  },
  settings: {
    get: () => http.get('/settings'),
    update: (payload) => http.put('/settings', payload),
    updateBulk: (payload) => http.put('/settings/bulk', payload),
    getProfile: () => http.get('/settings/profile'),
    updateProfile: (payload) => http.put('/settings/profile', payload),
    changePassword: (payload) => http.post('/settings/change-password', payload),
    financeSummary: (params) => http.get('/settings/finance/summary', { params }),
    revenueByUser: () => http.get('/settings/finance/by-user'),
    revenueByCompany: () => http.get('/settings/finance/by-company'),
    revenueByProduct: () => http.get('/settings/finance/by-product'),
    monthlyRevenue: (params) => http.get('/settings/finance/monthly', { params }),
  },
};
